#
# This file must be identical in: configs/ci-work/, app/ci-work/, restapi/ci-work/, summerwood/ci-work/, sync-server/ci-work/, viewer-html/ci-work/
#
version: "2.4"

x-common:
    &common-settings
    user: "$USER_ID:$GROUP_ID"
    env_file:
    - .env
    volumes:
    - ${CI_PROJECT_DIR}:/${CI_PROJECT_NAME}/
    - /tmp/:${HOME_DIR}/.ssh/
    - /etc/passwd:/etc/passwd:ro
    working_dir: /${CI_PROJECT_NAME}/
    restart: unless-stopped
    healthcheck:
      test: "echo 'HEALTHCHECK is OK'"
      interval: 5s
      timeout: 5s
      retries: 5
    command: 'bash -c "while true; do echo \"$$(date): HEARTBEAT event\"; sleep 60; done;"'

services:
  postgres:
    image: ${IMAGES_BASE_PATH}postgres:10.4
    hostname: postgres
    env_file:
    - .env
    volumes:
    - ${CI_PROJECT_DIR}:/${CI_PROJECT_NAME}/
    healthcheck:
      test: "psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1;'"
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  compiler:
    image: ${XPROJECT_COMPILER}
    hostname: compiler
    <<: *common-settings

  tester:
    image: ${XPROJECT_COMPILER}
    hostname: tester
    <<: *common-settings

  runner:
    image: ${XPROJECT_RUNNER}
    hostname: runner
    <<: *common-settings
